### ISSUE TITLE
[Question]: RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by IvanDeng0** [microsoft/MInference#58]
### Describe the issue

I encounted this error when running minference:
```
sampling_params = SamplingParams(temperature=0.8, top_p=0.95, min_tokens=0, max_tokens=500, n=2, best_of=3)
llm = LLM(model="/mnt/model/Qwen2-7B-Instruct", dtype="float16",tensor_parallel_size =2,disable_custom_all_reduce = True)
minference_patch = MInference("vllm", 'Qwen/Qwen2-7B-Instruct')
llm = minference_patch(llm)
```

```
Traceback (most recent call last):
  File "/mnt/inference/scripts/minference_script/minf.py", line 31, in <module>
    llm = LLM(model="/mnt/model/Qwen2-7B-Instruct", dtype="float16",tensor_parallel_size =2,disable_custom_all_reduce = True)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 155, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 441, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 251, in __init__
    self.model_executor = executor_class(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 47, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 123, in _init_executor
    self._run_workers("init_device")
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 178, in _run_workers
    driver_worker_output = driver_worker_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 132, in init_device
    init_worker_distributed_environment(self.parallel_config, self.rank,
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 343, in init_worker_distributed_environment
    init_distributed_environment(parallel_config.world_size, rank,
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 812, in init_distributed_environment
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 89, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1305, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/rendezvous.py", line 199, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout, use_libuv)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistStoreError: Timed out after 601 seconds waiting for clients. 1/2 clients joined.
```
 how to solve this issue?

**Comment by iofu728** [comment]
Hi @IvanDeng0, thank you for your support with MInference.

Could you please provide the environment information, such as CUDA version, Torch version, OS, etc.? Additionally, have you tried building from source using the following steps?
```bash
git clone https://github.com/microsoft/MInference
cd MInference
pip install -e .
```

**Comment by IvanDeng0** [comment]
Thanks for your reply, I've tried the method you mentioned, but the error keeps the same, my env info is following:
cuda 12.1
torch 2.3.1+cu12.1
vllm 0.5.3.post1
transformers 4.43.3
os ubuntu 22.04

**Comment by zh2333** [comment]
> Thanks for your reply, I've tried the method you mentioned, but the error keeps the same, my env info is following: cuda 12.1 torch 2.3.1+cu12.1 vllm 0.5.3.post1 transformers 4.43.3 os ubuntu 22.04
> 
> I have solved the error successfully, and i'll close this issue

I met the same problem as you. How did you solve it?
